# syntax=docker/dockerfile:1
FROM node:20-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV VITE_API_URL=
COPY . /app
RUN npm install
RUN npm run build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/dist /usr/share/nginx/html
COPY ./deployment/nginx.default.conf /etc/nginx/conf.d/default.conf