FROM node:20-alpine
WORKDIR /app

COPY ./package.json ./
COPY ./package-lock.json ./
COPY . .

ARG SECRET_PATH
COPY ${SECRET_PATH} ./gogogetaway.key

RUN npm install

EXPOSE 8080

CMD ["npm", "run", "start"]